### ISSUE TITLE
generate non-stacked objects like Clevr?

### ISSUE THREAD

**Issue by nanlliu** [IBM/photorealistic-blocksworld#4]
Im wondering if it is still possible to generate images like the original Clevr does. And stack objects when the new object has the same coordinates as some other objects already added in the scene?

**Comment by guicho271828** [comment]
Hi actually if you look at the "random" branch, which contains a significant refactoring, it actually does exactly that.

**Comment by nanlliu** [comment]
but it seems that it basically always stacks objects?

**Comment by nanlliu** [comment]
it seems that it always stacks objects?
